# Generated by Django 4.1.6 on 2023-02-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('password', models.IntegerField()),
                ('is_bool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infos',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('info', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_bool', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0, verbose_name='Korinishlar')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confapp.category1')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
                'ordering': ['created_at'],
            },
        ),
    ]
